version: '3.5'

services:
    
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_USER=root
    networks: 
      - nodenet
  
  node:
    build:
      context: ./node
      dockerfile: Dockerfile.prod
    image: netoalpha/node:prod
    container_name: node
    ports:
      - "3000"
    networks:
      - nodenet
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: netoalpha/nginx:prod
    container_name: nginx
    networks:
     - nodenet
    ports:
      - "8080:80"

networks:
  nodenet:
    driver: bridge
